name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    # Install Bun
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH  # Add Bun to the PATH for this job

    # Use Node.js (Optional, in case you need Node.js alongside Bun)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies using Bun
    - run: bun install
    
    # Build the project (if a build step exists in your package.json)
    - run: bun run build --if-present
    
    - run: |
        bun run start &  # Start the server in the background
        echo $! > pid.txt  # Save the process ID for later use
